name: Test

on:
    pull_request:
        branches: [main]
        paths-ignore:
            - "**/*.md"
            - "docs/**"
    push:
        branches: [main]
        paths-ignore:
            - "**/*.md"
            - "docs/**"

concurrency:
    group: test-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-frontend:
        name: Frontend Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run linter
              run: npm run lint

            - name: Run tests
              run: npm test

            - name: Build application
              run: npm run build

    test-backend:
        name: Backend Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt

            - name: Validate SAM template
              uses: aws-actions/setup-sam@v2

            - name: Validate template
              run: sam validate --lint

            - name: Run Python tests
              run: pytest tests/ -v

            - name: Run JavaScript tests
              run: npm test
